import * as openApi from "./openApi"

export const dummyClassGroupItems: openApi.ClassGroupItem[] = [
  {
    schedule_id: 1,
    student_id: 101,
    student_name_en: "Ahmed Hassan",
    student_name_ar: "أحمد حسن",
    day_label: "Monday",
    start_time: "09:00",
    end_time: "10:00",
    rrule_string: "FREQ=WEEKLY;BYDAY=MO",
    effective_from: "2026-01-15",
    effective_until: "2026-12-31",
    next_occurrence: "2026-04-21",
    total_lessons: 12,
    is_active: true,
  },
  {
    schedule_id: 2,
    student_id: 102,
    student_name_en: "Fatima Mohammed",
    student_name_ar: "فاطمة محمد",
    day_label: "Tuesday",
    start_time: "10:30",
    end_time: "11:30",
    rrule_string: "FREQ=WEEKLY;BYDAY=TU,TH",
    effective_from: "2026-02-01",
    effective_until: "2026-11-30",
    next_occurrence: "2026-04-22",
    total_lessons: 18,
    is_active: true,
  },
  {
    schedule_id: 3,
    student_id: 103,
    student_name_en: "Muhammad Ali",
    student_name_ar: "محمد علي",
    day_label: "Wednesday",
    start_time: "14:00",
    end_time: "15:00",
    rrule_string: "FREQ=WEEKLY;BYDAY=WE,FR",
    effective_from: "2026-01-20",
    effective_until: null,
    next_occurrence: "2026-04-23",
    total_lessons: 24,
    is_active: true,
  },
  {
    schedule_id: 4,
    student_id: 104,
    student_name_en: "Leila Ahmed",
    student_name_ar: "ليلى أحمد",
    day_label: "Thursday",
    start_time: "15:30",
    end_time: "16:30",
    rrule_string: "FREQ=WEEKLY;BYDAY=TH",
    effective_from: "2026-03-01",
    effective_until: "2026-08-31",
    next_occurrence: "2026-04-24",
    total_lessons: 8,
    is_active: true,
  },
  {
    schedule_id: 5,
    student_id: 105,
    student_name_en: "Karim Ibrahim",
    student_name_ar: "كريم إبراهيم",
    day_label: "Friday",
    start_time: "16:00",
    end_time: "17:00",
    rrule_string: null,
    effective_from: "2026-04-15",
    effective_until: "2026-04-15",
    next_occurrence: null,
    total_lessons: 1,
    is_active: false,
  },
  {
    schedule_id: 6,
    student_id: 106,
    student_name_en: "Noor Hassan",
    student_name_ar: "نور حسن",
    day_label: "Saturday",
    start_time: "11:00",
    end_time: "12:00",
    rrule_string: "FREQ=WEEKLY;BYDAY=SA,SU",
    effective_from: "2026-01-10",
    effective_until: "2026-06-30",
    next_occurrence: "2026-04-25",
    total_lessons: 15,
    is_active: true,
  },
  {
    schedule_id: 7,
    student_id: 107,
    student_name_en: "Zainab Khalil",
    student_name_ar: "زينب خليل",
    day_label: "Sunday",
    start_time: "13:00",
    end_time: "14:00",
    rrule_string: "FREQ=WEEKLY;BYDAY=SU",
    effective_from: "2026-02-15",
    effective_until: "2026-09-30",
    next_occurrence: "2026-04-26",
    total_lessons: 20,
    is_active: true,
  },
  {
    schedule_id: 8,
    student_id: 108,
    student_name_en: "Omar Samir",
    student_name_ar: "عمر سمير",
    day_label: "Monday",
    start_time: "17:00",
    end_time: "18:00",
    rrule_string: "FREQ=WEEKLY;BYDAY=MO,WE,FR",
    effective_from: "2026-03-15",
    effective_until: "2026-10-31",
    next_occurrence: "2026-04-21",
    total_lessons: 22,
    is_active: true,
  },
]

export const getDummyClassGroupItem = (id: number): openApi.ClassGroupItem | undefined => {
  return dummyClassGroupItems.find((item) => item.schedule_id === id)
}

export const getDummyClassGroupItemsByStudentId = (
  studentId: number,
): openApi.ClassGroupItem[] => {
  return dummyClassGroupItems.filter((item) => item.student_id === studentId)
}

export const getDummyActiveClassGroupItems = (): openApi.ClassGroupItem[] => {
  return dummyClassGroupItems.filter((item) => item.is_active)
}

export const getDummyClassGroupItemsByDay = (day: string): openApi.ClassGroupItem[] => {
  return dummyClassGroupItems.filter((item) => item.day_label === day)
}

export const dummyHistory: openApi.LessonRead[] = [
  {
    id: 1,
    student_id: 101,
    sheikh_id: 201,
    schedule_id: 1,
    recurrence_group_id: null,
    date: "2026-04-15",
    type: openApi.LessonType.NewMemorization,
    pass_fail: true,
    attendance: openApi.AttendanceStatus.Present,
    absence_reason: null,
    student_notes: "I found this lesson very clear and easy to understand.",
    sheikh_notes: "Excellent memorization. Student grasped the concepts quickly.",
    what_is_heard_from_sheikh: "Student understood the concepts very quickly.",
    homework: "Review Al-Fatiha verses 1-7",
  },
  {
    id: 2,
    student_id: 101,
    sheikh_id: 201,
    schedule_id: 1,
    recurrence_group_id: null,
    date: "2026-04-14",
    type: openApi.LessonType.Revision,
    pass_fail: true,
    attendance: openApi.AttendanceStatus.Present,
    absence_reason: null,
    student_notes: null,
    sheikh_notes: "Good revision. Student needs more practice with pronunciation.",
    what_is_heard_from_sheikh: "Student is improving pronunciation skills.",
    homework: "Practice pronunciation of Al-Baqarah verses",
  },
  {
    id: 3,
    student_id: 101,
    sheikh_id: 201,
    schedule_id: 1,
    recurrence_group_id: null,
    date: "2026-04-13",
    type: openApi.LessonType.Evaluation,
    pass_fail: true,
    attendance: openApi.AttendanceStatus.Late,
    absence_reason: null,
    student_notes: "Felt a bit rushed during evaluation.",
    sheikh_notes: "Student arrived 10 minutes late. Overall performance was acceptable.",
    what_is_heard_from_sheikh: "Student showed understanding despite time pressure.",
    homework: "Continue memorization practice",
  },
  {
    id: 4,
    student_id: 104,
    sheikh_id: 204,
    schedule_id: 4,
    recurrence_group_id: null,
    date: "2026-04-12",
    type: openApi.LessonType.NewMemorization,
    pass_fail: false,
    attendance: openApi.AttendanceStatus.Present,
    absence_reason: null,
    student_notes: "Found this surah difficult. Need more time to memorize.",
    sheikh_notes: "Student struggled with some verses. Recommended more practice time between sessions.",
    what_is_heard_from_sheikh: "Student needs additional support and practice time.",
    homework: "Review and practice Surah An-Nisa verses daily",
  },
  {
    id: 5,
    student_id: 105,
    sheikh_id: 205,
    schedule_id: 5,
    recurrence_group_id: null,
    date: "2026-04-11",
    type: openApi.LessonType.Makeup,
    pass_fail: true,
    attendance: openApi.AttendanceStatus.Absent,
    absence_reason: "Sick leave - had a fever",
    student_notes: null,
    sheikh_notes: "Make-up lesson scheduled. Student recovering from illness.",
    what_is_heard_from_sheikh: null,
    homework: null,
  },
  {
    id: 6,
    student_id: 106,
    sheikh_id: 206,
    schedule_id: 6,
    recurrence_group_id: null,
    date: "2026-04-10",
    type: openApi.LessonType.Revision,
    pass_fail: true,
    attendance: openApi.AttendanceStatus.Present,
    absence_reason: null,
    student_notes: "I'm confident with this surah now.",
    sheikh_notes: "Excellent revision session. Student is ready to move to the next surah.",
    what_is_heard_from_sheikh: "Student is showing excellent progress and confidence.",
    homework: "Begin memorization of the next surah",
  },
  {
    id: 7,
    student_id: 107,
    sheikh_id: 207,
    schedule_id: 7,
    recurrence_group_id: null,
    date: "2026-04-09",
    type: openApi.LessonType.Evaluation,
    pass_fail: true,
    attendance: openApi.AttendanceStatus.Excused,
    absence_reason: "Had to leave 5 minutes early for family commitment",
    student_notes: null,
    sheikh_notes: "Student left early but completed the evaluation. Performance was very good.",
    what_is_heard_from_sheikh: "Student demonstrated strong comprehension despite time constraint.",
    homework: "Review and consolidate learned material",
  },
  {
    id: 8,
    student_id: 108,
    sheikh_id: 208,
    schedule_id: 8,
    recurrence_group_id: null,
    date: "2026-04-08",
    type: openApi.LessonType.NewMemorization,
    pass_fail: true,
    attendance: openApi.AttendanceStatus.Present,
    absence_reason: null,
    student_notes: "This surah is longer but the meaning helps with memorization.",
    sheikh_notes: "Good progress. Student shows good understanding of context.",
    what_is_heard_from_sheikh: "Student is making steady progress with contextual understanding.",
    homework: "Continue memorization and understanding of current surah",
  },
]

export const getDummyLessonHistory = (lessonId: number): openApi.ClassHistoryResponse | undefined => {
  const lesson = dummyHistory.find((item) => item.id === lessonId)
  if (lesson) {
    return {
      total: 1,
      lessons: [lesson],
    }
  }
  return undefined
}
