import * as openApi from "./openApi";

export const dummyLessons: openApi.LessonRead[] = [
  {
    id: 1,
    student_id: 101,
    sheikh_id: 201,
    schedule_id: 301,
    date: "2026-02-06",
    type: openApi.LessonType.NewMemorization,
    surah_name: "Al-Fatiha",
    juz_number: 1,
    ayah_from: 1,
    ayah_to: 7,
    quality: openApi.LessonQuality.Excellent,
    attendance: openApi.AttendanceStatus.Present,
    absence_reason: null,
    student_notes: "I found the new memorization lesson to be very engaging and rewarding. I am proud of my progress in memorizing the first 7 ayahs of Al-Fatiha. I will continue practicing daily to perfect the recitation.",
    sheikh_notes: "Great job on the new memorization! Keep up the good work and focus on perfecting the recitation of the first 7 ayahs. For the next lesson, we will continue with Al-Fatiha and aim to memorize ayahs 8 to 20. Make sure to practice daily and let me know if you have any questions or need additional support.",
    next_homework_type: openApi.LessonType.NewMemorization,
    next_homework_surah: "Al-Fatiha",
    next_homework_ayah_from: 8,
    next_homework_ayah_to: 20,
    next_homework_due_date: "2026-02-13",
  },
  {
    id: 2,
    student_id: 102,
    sheikh_id: 201,
    schedule_id: 302,
    date: "2026-02-05",
    type: openApi.LessonType.Revision,
    surah_name: "Al-Baqarah",
    juz_number: 1,
    ayah_from: 1,
    ayah_to: 50,
    quality: openApi.LessonQuality.VeryGood,
    attendance: openApi.AttendanceStatus.Present,
    absence_reason: null,
    student_notes: "The revision session went well. I was able to recall most of the ayahs without much difficulty. I felt confident throughout the lesson.",
    sheikh_notes: "Excellent revision performance! Your memory is strong and your recitation is clear. Continue reviewing the first 50 ayahs and prepare for the next evaluation.",
    next_homework_type: openApi.LessonType.Revision,
    next_homework_surah: "Al-Baqarah",
    next_homework_ayah_from: 51,
    next_homework_ayah_to: 100,
    next_homework_due_date: "2026-02-12",
  },
  {
    id: 3,
    student_id: 103,
    sheikh_id: 202,
    schedule_id: null,
    date: "2026-02-04",
    type: openApi.LessonType.Evaluation,
    surah_name: "Al-Imran",
    juz_number: 3,
    ayah_from: 1,
    ayah_to: 30,
    quality: openApi.LessonQuality.Good,
    attendance: openApi.AttendanceStatus.Present,
    absence_reason: null,
    student_notes: "I performed well in the evaluation. I was able to recite most of the ayahs accurately, though there were a few minor pronunciation issues.",
    sheikh_notes: "Good evaluation results. Your memorization is solid, but pay attention to proper tajweed rules, especially in the middle sections. Practice the diacritical marks more carefully.",
    next_homework_type: openApi.LessonType.NewMemorization,
    next_homework_surah: "Al-Imran",
    next_homework_ayah_from: 31,
    next_homework_ayah_to: 60,
    next_homework_due_date: "2026-02-11",
  },
  {
    id: 4,
    student_id: 104,
    sheikh_id: 202,
    schedule_id: 303,
    date: "2026-02-03",
    type: openApi.LessonType.Makeup,
    surah_name: "An-Nisa",
    juz_number: 4,
    ayah_from: 1,
    ayah_to: 25,
    quality: openApi.LessonQuality.Fair,
    attendance: openApi.AttendanceStatus.Late,
    absence_reason: "Traffic delay",
    student_notes: "I struggled with this makeup lesson. I need more time to practice before attempting another evaluation. Some ayahs are still unclear in my memory.",
    sheikh_notes: "The makeup lesson showed some gaps in memorization. I recommend taking more time for practice before the next session. Schedule an additional practice session if possible.",
    next_homework_type: openApi.LessonType.Revision,
    next_homework_surah: "An-Nisa",
    next_homework_ayah_from: 1,
    next_homework_ayah_to: 25,
    next_homework_due_date: "2026-02-10",
  },
  {
    id: 5,
    student_id: 105,
    sheikh_id: 201,
    schedule_id: 304,
    date: "2026-02-02",
    type: openApi.LessonType.NewMemorization,
    surah_name: "Al-Maidah",
    juz_number: 6,
    ayah_from: 1,
    ayah_to: 20,
    quality: openApi.LessonQuality.NeedsImprovement,
    attendance: openApi.AttendanceStatus.Absent,
    absence_reason: "Illness",
    student_notes: "I was not able to attend the lesson due to illness. I will catch up when I feel better.",
    sheikh_notes: "Student was absent due to illness. Once they recover, we should focus on a comprehensive review of the previously covered material before continuing with new memorization.",
    next_homework_type: openApi.LessonType.Revision,
    next_homework_surah: "Al-Maidah",
    next_homework_ayah_from: 1,
    next_homework_ayah_to: 20,
    next_homework_due_date: "2026-02-09",
  },
];

export const dummySchedules: openApi.ScheduleRead[] = [
    {
        sheikh_id: 1,
        student_id: 2,
        day_of_week: 1,
        id: 123,
        start_time: "2024-01-01T10:00:00Z",
        end_time: "2024-01-01T11:00:00Z",
        is_recurring: true,
        is_active: true,
        effective_from: "2024-01-01T00:00:00Z",
        effective_until: "2024-12-31T23:59:59Z",
        notes: "This is a sample schedule.",
        cancellation_reason: ""
    },
    {
        sheikh_id: 1,
        student_id: 3,
        day_of_week: 3,
        id: 1244,
        start_time: "2024-01-03T14:00:00Z",
        end_time: "2024-01-03T15:00:00Z",
        is_recurring: false,
        is_active: false,
        effective_from: "2024-01-03T00:00:00Z",
        effective_until: "2024-01-03T23:59:59Z",
        notes: "This schedule is not recurring.",
        cancellation_reason: "Student requested cancellation."
    },
{
        sheikh_id: 1,
        student_id: 3,
        day_of_week: 3,
        id: 12435,
        start_time: "2024-01-03T14:00:00Z",
        end_time: "2024-01-03T15:00:00Z",
        is_recurring: false,
        is_active: false,
        effective_from: "2024-01-03T00:00:00Z",
        effective_until: "2024-01-03T23:59:59Z",
        notes: "This schedule is not recurring.",
        cancellation_reason: "Student requested cancellation."
    },
{
        sheikh_id: 1,
        student_id: 3,
        day_of_week: 3,
        id: 12443,
        start_time: "2024-01-03T14:00:00Z",
        end_time: "2024-01-03T15:00:00Z",
        is_recurring: false,
        is_active: false,
        effective_from: "2024-01-03T00:00:00Z",
        effective_until: "2024-01-03T23:59:59Z",
        notes: "This schedule is not recurring.",
        cancellation_reason: "Student requested cancellation."
    },
{
        sheikh_id: 1,
        student_id: 3,
        day_of_week: 3,
        id: 1324,
        start_time: "2024-01-03T14:00:00Z",
        end_time: "2024-01-03T15:00:00Z",
        is_recurring: false,
        is_active: false,
        effective_from: "2024-01-03T00:00:00Z",
        effective_until: "2024-01-03T23:59:59Z",
        notes: "This schedule is not recurring.",
        cancellation_reason: "Student requested cancellation."
    }
];

export const dummyLibraryItems: openApi.LibraryItemRead[] = [
  {
    id: 1,
    sheikh_id: 201,
    title: "Understanding Tajweed Rules",
    description: "A comprehensive guide to proper Quran recitation with tajweed rules explained in detail.",
    category: "Tajweed",
    tags: ["tajweed", "recitation", "quran", "rules"],
    thumbnail_image_path: "/images/library/tajweed.jpg",
    external_url: "https://example.com/tajweed-guide",
    access_level: openApi.LibraryAccessLevel.AllStudents,
    download_count: 145,
    view_count: 523,
    is_active: true,
  },
  {
    id: 2,
    sheikh_id: 201,
    title: "Surah Al-Fatiha: Detailed Analysis",
    description: "An in-depth exploration of Surah Al-Fatiha with historical context and linguistic analysis.",
    category: "Surah Analysis",
    tags: ["al-fatiha", "quran", "analysis", "linguistics"],
    thumbnail_image_path: "/images/library/al-fatiha.jpg",
    external_url: "https://example.com/al-fatiha-analysis",
    access_level: openApi.LibraryAccessLevel.AllStudents,
    download_count: 234,
    view_count: 876,
    is_active: true,
  },
  {
    id: 3,
    sheikh_id: 202,
    title: "Memorization Techniques for Quran",
    description: "Effective strategies and techniques to improve Quranic memorization skills.",
    category: "Study Methods",
    tags: ["memorization", "techniques", "study", "hifz"],
    thumbnail_image_path: "/images/library/memorization.jpg",
    external_url: "https://example.com/memorization-techniques",
    access_level: openApi.LibraryAccessLevel.SpecificStudents,
    download_count: 89,
    view_count: 342,
    is_active: true,
  },
  {
    id: 4,
    sheikh_id: 202,
    title: "Islamic History: The Era of the Prophet",
    description: "A historical overview of Prophet Muhammad's life and the early Islamic period.",
    category: "History",
    tags: ["history", "prophet", "islamic", "era"],
    thumbnail_image_path: "/images/library/history.jpg",
    external_url: "https://example.com/islamic-history",
    access_level: openApi.LibraryAccessLevel.AllStudents,
    download_count: 156,
    view_count: 612,
    is_active: true,
  },
  {
    id: 5,
    sheikh_id: 203,
    title: "Arabic Grammar Essentials",
    description: "Fundamental rules of Arabic grammar necessary for understanding classical Arabic texts.",
    category: "Language",
    tags: ["arabic", "grammar", "language", "linguistics"],
    thumbnail_image_path: "/images/library/arabic-grammar.jpg",
    external_url: "https://example.com/arabic-grammar",
    access_level: openApi.LibraryAccessLevel.Groups,
    download_count: 201,
    view_count: 754,
    is_active: true,
  },
  {
    id: 6,
    sheikh_id: 203,
    title: "Quranic Vocabulary Guide",
    description: "A comprehensive dictionary of Quranic words with meanings and contextual usage.",
    category: "Vocabulary",
    tags: ["vocabulary", "quran", "dictionary", "words"],
    thumbnail_image_path: "/images/library/vocabulary.jpg",
    external_url: "https://example.com/quran-vocabulary",
    access_level: openApi.LibraryAccessLevel.AllStudents,
    download_count: 178,
    view_count: 645,
    is_active: false,
  }
];

export const dummyStudents: openApi.StudentRead[] = [
  {
    id: 101,
    user_id: 1001,
    sheikh_id: 201,
    full_name_arabic: "أحمد بن محمد الفاروق",
    full_name_english: "Ahmed bin Mohammed Al-Farouq",
    date_of_birth: "1998-05-15",
    phone: "+966501234567",
    timezone: "Asia/Riyadh",
    registration_status: openApi.RegistrationStatus.Approved,
    status: openApi.StudentStatus.Active,
    current_juz: 3,
    current_surah: "Al-Imran",
    current_ayah: 45,
    lessons_per_week: 3,
    lesson_rate: 50,
    billing_cycle: openApi.BillingCycle.Monthly,
    private_notes: "Dedicated student with excellent memory. Prefers morning sessions.",
    special_notes: "Has completed memorization of Juz 1 and 2.",
  },
  {
    id: 102,
    user_id: 1002,
    sheikh_id: 201,
    full_name_arabic: "يوسف عبدالله العمري",
    full_name_english: "Youssef Abdullah Al-Omari",
    date_of_birth: "2005-08-22",
    phone: "+966509876543",
    timezone: "Asia/Riyadh",
    registration_status: openApi.RegistrationStatus.Approved,
    status: openApi.StudentStatus.Active,
    current_juz: 1,
    current_surah: "Al-Baqarah",
    current_ayah: 100,
    lessons_per_week: 2,
    lesson_rate: 45,
    billing_cycle: openApi.BillingCycle.Weekly,
    private_notes: "Young student, needs encouragement. Good progress so far.",
    special_notes: "Started memorization journey 3 months ago.",
  },
  {
    id: 103,
    user_id: 1003,
    sheikh_id: 202,
    full_name_arabic: "عمر سعيد الحسني",
    full_name_english: "Omar Saeed Al-Hasani",
    date_of_birth: "1990-12-10",
    phone: "+971501122334",
    timezone: "Asia/Dubai",
    registration_status: openApi.RegistrationStatus.Approved,
    status: openApi.StudentStatus.OnHold,
    current_juz: 10,
    current_surah: "Al-Anfal",
    current_ayah: 30,
    lessons_per_week: 2,
    lesson_rate: 60,
    billing_cycle: openApi.BillingCycle.Monthly,
    private_notes: "Taking a break due to work commitments. Will resume next month.",
    special_notes: "Advanced student with 9 juz completed.",
  },
  {
    id: 104,
    user_id: 1004,
    sheikh_id: 202,
    full_name_arabic: "خالد إبراهيم المنصور",
    full_name_english: "Khaled Ibrahim Al-Mansour",
    date_of_birth: "2000-03-25",
    phone: "+965512345678",
    timezone: "Asia/Kuwait",
    registration_status: openApi.RegistrationStatus.Pending,
    status: openApi.StudentStatus.Inactive,
    current_juz: null,
    current_surah: null,
    current_ayah: null,
    lessons_per_week: 2,
    lesson_rate: null,
    billing_cycle: openApi.BillingCycle.Monthly,
    private_notes: "New registration, awaiting schedule confirmation.",
    special_notes: "Beginner level, no prior memorization experience.",
  },
  {
    id: 105,
    user_id: 1005,
    sheikh_id: 201,
    full_name_arabic: "محمد علي الرشيد",
    full_name_english: "Mohammed Ali Al-Rashid",
    date_of_birth: "1985-07-08",
    phone: "+966555667788",
    timezone: "Asia/Riyadh",
    registration_status: openApi.RegistrationStatus.Pending,
    status: openApi.StudentStatus.Graduated,
    current_juz: 30,
    current_surah: "An-Nas",
    current_ayah: 6,
    lessons_per_week: 1,
    lesson_rate: 40,
    billing_cycle: openApi.BillingCycle.Monthly,
    private_notes: "Completed full Quran memorization. Now doing revision sessions.",
    special_notes: "Hafiz - completed memorization on 2025-12-15.",
  },
  {
    id: 106,
    user_id: null,
    sheikh_id: 203,
    full_name_arabic: "عبدالرحمن فهد القحطاني",
    full_name_english: "Abdulrahman Fahad Al-Qahtani",
    date_of_birth: "2010-01-20",
    phone: "+966501112233",
    timezone: "Asia/Riyadh",
    registration_status: openApi.RegistrationStatus.Rejected,
    status: openApi.StudentStatus.Active,
    current_juz: 1,
    current_surah: "Al-Fatiha",
    current_ayah: 7,
    lessons_per_week: 4,
    lesson_rate: 35,
    billing_cycle: openApi.BillingCycle.Weekly,
    private_notes: "Child student, parent manages account. Very enthusiastic.",
    special_notes: "Just started with Al-Fatiha. Learning tajweed basics.",
  },
];

export const dummyInvoices: openApi.InvoiceRead[] = [
  {
    id: 1,
    student_id: 101,
    sheikh_id: 201,
    invoice_number: "INV-2026-0001",
    period_from: "2026-01-01",
    period_to: "2026-01-31",
    total_amount: 600,
    currency: "SAR",
    status: openApi.InvoiceStatus.Paid,
    generated_date: "2026-02-01",
    due_date: "2026-02-15",
    paid_date: "2026-02-10",
    payment_method: "Bank Transfer",
    payment_reference: "TRX-20260210-001",
    payment_notes: "Paid in full via bank transfer.",
    pdf_path: "/invoices/2026/INV-2026-0001.pdf",
    pdf_generated_at: "2026-02-01T10:30:00Z",
  },
  {
    id: 2,
    student_id: 102,
    sheikh_id: 201,
    invoice_number: "INV-2026-0002",
    period_from: "2026-01-01",
    period_to: "2026-01-31",
    total_amount: 360,
    currency: "SAR",
    status: openApi.InvoiceStatus.Sent,
    generated_date: "2026-02-01",
    due_date: "2026-02-15",
    paid_date: null,
    payment_method: null,
    payment_reference: null,
    payment_notes: null,
    pdf_path: "/invoices/2026/INV-2026-0002.pdf",
    pdf_generated_at: "2026-02-01T11:00:00Z",
  },
  {
    id: 3,
    student_id: 103,
    sheikh_id: 202,
    invoice_number: "INV-2026-0003",
    period_from: "2025-12-01",
    period_to: "2025-12-31",
    total_amount: 480,
    currency: "AED",
    status: openApi.InvoiceStatus.Overdue,
    generated_date: "2026-01-01",
    due_date: "2026-01-15",
    paid_date: null,
    payment_method: null,
    payment_reference: null,
    payment_notes: null,
    pdf_path: "/invoices/2026/INV-2026-0003.pdf",
    pdf_generated_at: "2026-01-01T09:15:00Z",
  },
  {
    id: 4,
    student_id: 105,
    sheikh_id: 201,
    invoice_number: "INV-2026-0004",
    period_from: "2026-01-01",
    period_to: "2026-01-31",
    total_amount: 160,
    currency: "SAR",
    status: openApi.InvoiceStatus.Paid,
    generated_date: "2026-02-01",
    due_date: "2026-02-15",
    paid_date: "2026-02-05",
    payment_method: "Credit Card",
    payment_reference: "CC-20260205-789",
    payment_notes: "Monthly revision session fees.",
    pdf_path: "/invoices/2026/INV-2026-0004.pdf",
    pdf_generated_at: "2026-02-01T14:20:00Z",
  },
  {
    id: 5,
    student_id: 106,
    sheikh_id: 203,
    invoice_number: "INV-2026-0005",
    period_from: "2026-01-27",
    period_to: "2026-02-02",
    total_amount: 140,
    currency: "SAR",
    status: openApi.InvoiceStatus.Generated,
    generated_date: "2026-02-03",
    due_date: "2026-02-10",
    paid_date: null,
    payment_method: null,
    payment_reference: null,
    payment_notes: null,
    pdf_path: null,
    pdf_generated_at: null,
  },
  {
    id: 6,
    student_id: 101,
    sheikh_id: 201,
    invoice_number: "INV-2025-0048",
    period_from: "2025-11-01",
    period_to: "2025-11-30",
    total_amount: 600,
    currency: "SAR",
    status: openApi.InvoiceStatus.Cancelled,
    generated_date: "2025-12-01",
    due_date: "2025-12-15",
    paid_date: null,
    payment_method: null,
    payment_reference: null,
    payment_notes: "Invoice cancelled due to billing error. New invoice generated.",
    pdf_path: "/invoices/2025/INV-2025-0048.pdf",
    pdf_generated_at: "2025-12-01T08:45:00Z",
  },
];

export const dummyProfile: openApi.StudentSelfRead = {
  id: 101,
  user_id: 1001,
  full_name_arabic: "أحمد محمد علي",
  full_name_english: "Ahmed Mohammed Ali",
  date_of_birth: "1995-03-15",
  phone: "+966 50 123 4567",
  timezone: "Asia/Riyadh",
  registration_status: openApi.RegistrationStatus.Approved,
  status: openApi.StudentStatus.Active,
  current_juz: 5,
  current_surah: "An-Nisa",
  current_ayah: 23,
  lessons_per_week: 3,
  lesson_rate: 50,
  billing_cycle: openApi.BillingCycle.Monthly,
  special_notes: "Student prefers morning lessons. Has excellent tajweed skills and is progressing well through the memorization curriculum. Focus on revision of earlier juz during weekly sessions.",
};