import * as openApi from "./openApi";

export const dummyLessons: openApi.LessonRead[] = [
  {
    id: 1,
    student_id: 101,
    sheikh_id: 201,
    schedule_id: 301,
    date: "2026-02-06",
    type: openApi.LessonType.NewMemorization,
    surah_name: "Al-Fatiha",
    juz_number: 1,
    ayah_from: 1,
    ayah_to: 7,
    quality: openApi.LessonQuality.Excellent,
    pass_fail: true,
    attempts: 1,
    attendance: openApi.AttendanceStatus.Present,
    absence_reason: null,
    student_notes: "I found the new memorization lesson to be very engaging and rewarding. I am proud of my progress in memorizing the first 7 ayahs of Al-Fatiha. I will continue practicing daily to perfect the recitation.",
    sheikh_notes: "Great job on the new memorization! Keep up the good work and focus on perfecting the recitation of the first 7 ayahs. For the next lesson, we will continue with Al-Fatiha and aim to memorize ayahs 8 to 20. Make sure to practice daily and let me know if you have any questions or need additional support.",
    next_homework_type: openApi.LessonType.NewMemorization,
    next_homework_surah: "Al-Fatiha",
    next_homework_ayah_from: 8,
    next_homework_ayah_to: 20,
    next_homework_due_date: "2026-02-13",
  },
  {
    id: 2,
    student_id: 102,
    sheikh_id: 201,
    schedule_id: 302,
    date: "2026-02-05",
    type: openApi.LessonType.Revision,
    surah_name: "Al-Baqarah",
    juz_number: 1,
    ayah_from: 1,
    ayah_to: 50,
    quality: openApi.LessonQuality.VeryGood,
    pass_fail: true,
    attempts: 2,
    attendance: openApi.AttendanceStatus.Present,
    absence_reason: null,
    student_notes: "The revision session went well. I was able to recall most of the ayahs without much difficulty. I felt confident throughout the lesson.",
    sheikh_notes: "Excellent revision performance! Your memory is strong and your recitation is clear. Continue reviewing the first 50 ayahs and prepare for the next evaluation.",
    next_homework_type: openApi.LessonType.Revision,
    next_homework_surah: "Al-Baqarah",
    next_homework_ayah_from: 51,
    next_homework_ayah_to: 100,
    next_homework_due_date: "2026-02-12",
  },
  {
    id: 3,
    student_id: 103,
    sheikh_id: 202,
    schedule_id: null,
    date: "2026-02-04",
    type: openApi.LessonType.Evaluation,
    surah_name: "Al-Imran",
    juz_number: 3,
    ayah_from: 1,
    ayah_to: 30,
    quality: openApi.LessonQuality.Good,
    pass_fail: true,
    attempts: 1,
    attendance: openApi.AttendanceStatus.Present,
    absence_reason: null,
    student_notes: "I performed well in the evaluation. I was able to recite most of the ayahs accurately, though there were a few minor pronunciation issues.",
    sheikh_notes: "Good evaluation results. Your memorization is solid, but pay attention to proper tajweed rules, especially in the middle sections. Practice the diacritical marks more carefully.",
    next_homework_type: openApi.LessonType.NewMemorization,
    next_homework_surah: "Al-Imran",
    next_homework_ayah_from: 31,
    next_homework_ayah_to: 60,
    next_homework_due_date: "2026-02-11",
  },
  {
    id: 4,
    student_id: 104,
    sheikh_id: 202,
    schedule_id: 303,
    date: "2026-02-03",
    type: openApi.LessonType.Makeup,
    surah_name: "An-Nisa",
    juz_number: 4,
    ayah_from: 1,
    ayah_to: 25,
    quality: openApi.LessonQuality.Fair,
    pass_fail: false,
    attempts: 3,
    attendance: openApi.AttendanceStatus.Late,
    absence_reason: "Traffic delay",
    student_notes: "I struggled with this makeup lesson. I need more time to practice before attempting another evaluation. Some ayahs are still unclear in my memory.",
    sheikh_notes: "The makeup lesson showed some gaps in memorization. I recommend taking more time for practice before the next session. Schedule an additional practice session if possible.",
    next_homework_type: openApi.LessonType.Revision,
    next_homework_surah: "An-Nisa",
    next_homework_ayah_from: 1,
    next_homework_ayah_to: 25,
    next_homework_due_date: "2026-02-10",
  },
  {
    id: 5,
    student_id: 105,
    sheikh_id: 201,
    schedule_id: 304,
    date: "2026-02-02",
    type: openApi.LessonType.NewMemorization,
    surah_name: "Al-Maidah",
    juz_number: 6,
    ayah_from: 1,
    ayah_to: 20,
    quality: openApi.LessonQuality.NeedsImprovement,
    pass_fail: false,
    attempts: 4,
    attendance: openApi.AttendanceStatus.Absent,
    absence_reason: "Illness",
    student_notes: "I was not able to attend the lesson due to illness. I will catch up when I feel better.",
    sheikh_notes: "Student was absent due to illness. Once they recover, we should focus on a comprehensive review of the previously covered material before continuing with new memorization.",
    next_homework_type: openApi.LessonType.Revision,
    next_homework_surah: "Al-Maidah",
    next_homework_ayah_from: 1,
    next_homework_ayah_to: 20,
    next_homework_due_date: "2026-02-09",
  },
];
